# Generated by Django 5.0.7 on 2024-07-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_count_app', '0002_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='year_founded',
            field=models.CharField(max_length=10),
        ),
    ]
