# Generated by Django 5.0.7 on 2024-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_count_app', '0003_alter_data_year_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='current_employee_estimate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='domain',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='industry',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='linkedin_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='locality',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='size_range',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='state',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='total_employee_estimate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='year_founded',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
